title: My jouney
author: aHafiz C.
email: kopishitam@disroot.org
description: > # this means to ignore newlines until "baseurl:"
  This site aim my jouney in the world as a lifetime learner

# social links
twitter_username: kopishitam # DO NOT include the @ character, or else the build will fail!
github_username:  apiz19 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

# using theme
theme: minima
